### ISSUE TITLE
Testing and Debugging

### ISSUE THREAD

**Issue by awarbler** [awarbler/SeniorProject#85]
Test your Arduino code to ensure it can successfully connect to the Nest API and control your thermostat. Debug any issues that arise during testing.

**Comment by habibur4340** [comment]
Hey @awarbler  👋,

Just finished a round of testing on our Arduino code for connecting to the Nest API and controlling the thermostat. Ran into a few snags along the way. To streamline our testing and debugging process, I highly recommend we check out Apidog.

[Apidog](https://apidog.com/) could be a great asset for us to test and ensure our code interacts seamlessly with the Nest API. It offers detailed insights that can help us quickly pinpoint and resolve any issues.

Quick steps with Apidog:

Set up Apidog to monitor our Arduino to Nest API connection.
Test endpoint accessibility and functionality.
Use feedback to debug and refine our code.
Thoughts on giving Apidog a try to make our development process smoother?

Cheers! 🛠️
